// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('~/components/_base/Button.vue')['default']
    BaseFadeTransition: typeof import('~/components/_base/FadeTransition.vue')['default']
    BaseFadeTransitionGroup: typeof import('~/components/_base/FadeTransitionGroup.vue')['default']
    BaseInput: typeof import('~/components/_base/Input.vue')['default']
    BaseLink: typeof import('~/components/_base/Link.vue')['default']
    BaseRouterView: typeof import('~/components/_base/RouterView.vue')['default']
    BaseScroll: typeof import('~/components/_base/Scroll.vue')['default']
    BaseToggler: typeof import('~/components/_base/Toggler.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
